import xym.test_cases.test_fee_one
import xym.test_cases.test_fee_data.fee_one_data
import xym.test_cases.test_fee_data.fee_order_data
import xym.test_cases.test_fee_electric
import xym.test_cases.test_order_activity
import xym.request.mybaiduTK
import xym.request.obtainTK
import HTMLTestRunner
import unittest
import datetime
import time

if __name__ == "__main__":
    # 初始化
    fee = xym.test_cases.test_order_activity.order()
    # 添加新用户
    # print(fee.newuser())
    # 找老用户
    fee.order_user()
    # 匹配老用户地址
    fee.order_address()
    # 查询开单用户会员卡
    fee.order_card()
    # 查询所关联的活动
    fee.activities()
    # 商户正常开单
    fee.prequalification_01()
    fee.prequalification_02()
    fee.prequalification_03()
    fee.prequalification_04()
    fee.prequalification_05()
    fee.prequalification_06()
    fee.prequalification_07()
    fee.prequalification_08()
    fee.prequalification_09()
    fee.prequalification_10()
    fee.prequalification_11()
    fee.prequalification_12()
    fee.prequalification_13()
    fee.prequalification_14()
    fee.prequalification_15()
    fee.prequalification_16()
    fee.prequalification_17()
    fee.prequalification_18()
    fee.prequalification_19()
    fee.prequalification_20()
    fee.prequalification_20()
    fee.prequalification_21()
    fee.prequalification_22()
    fee.prequalification_23()
    fee.prequalification_24()
    fee.prequalification_25()
    fee.prequalification_26()
    fee.prequalification_27()
    fee.prequalification_28()
    fee.prequalification_29()
    fee.prequalification_30()
    fee.prequalification_31()
    fee.prequalification_32()
    fee.prequalification_33()
    fee.prequalification_34()
    fee.prequalification_35()
    fee.prequalification_36()
    fee.prequalification_37()
    fee.prequalification_38()
    fee.prequalification_39()
    fee.prequalification_40()
    fee.prequalification_41()
    fee.prequalification_42()
    fee.prequalification_43()
    fee.prequalification_44()
    fee.prequalification_45()
    fee.prequalification_46()
    fee.prequalification_47()
    fee.prequalification_48()
    fee.prequalification_49()
    fee.prequalification_50()
    fee.prequalification_51()
    fee.prequalification_52()
    fee.prequalification_53()
    fee.prequalification_54()
    fee.prequalification_55()
    fee.prequalification_56()
    fee.prequalification_57()
    fee.prequalification_58()
    fee.prequalification_59()
    fee.prequalification_60()
    fee.prequalification_61()
    fee.prequalification_61()
    fee.prequalification_62()
    fee.prequalification_63()
    fee.prequalification_64()
    fee.prequalification_65()
    fee.prequalification_66()
    fee.prequalification_67()
    fee.prequalification_68()
    fee.prequalification_69()
    fee.prequalification_70()
    # 商户异常开单
    fee.prequalification_001()
    fee.prequalification_002()
    fee.prequalification_003()
    fee.prequalification_004()
    fee.prequalification_005()
    fee.prequalification_006()
    fee.prequalification_007()
    fee.prequalification_008()
    fee.prequalification_009()
    fee.prequalification_010()

    # 订单查询
    print(fee.query_order())
    fee.query_order_tbpaid()
    fee.query_order_tbprequal()
    fee.query_order_customeraut()
    fee.query_order_merchantaut()
    fee.query_order_tbcompleted()
    fee.query_orde_completed()
    fee.query_order_returned()
    fee.query_order_tbreviewed()
    fee.query_order_auditfailed()
    fee.query_order_modifycustomer()
    fee.query_order_modifymerchant()
    fee.query_order_passprequal()
    fee.query_order_chargeback()
    # 取消待支付订单
    fee.tobepaid()
    fee.paid()


    qw = xym.test_cases.test_order_activity.authority()   #  商场开启订单权限
    # qw.order_qpproval_authority_01()
    # qw.order_qpproval_authority_02()
    # qw.order_qpproval_authority_03()
    # qw.order_qpproval_authority_04()
    # qw.order_qpproval_authority_05()
    # qw.order_qpproval_authority_06()
    # qw.order_qpproval_authority_07()
    # qw.order_qpproval_authority_08()
    # qw.order_qpproval_authority_09()
    # qw.order_qpproval_authority_10()
    # qw.order_qpproval_authority_11()
    # qw.order_qpproval_authority_12()
    # qw.order_qpproval_authority_13()
    # qw.order_qpproval_authority_14()